server:
  port: ${APP_PORT:8080}

spring:
  application:
    name: ecomap
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:ecomap}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:12345}
  jpa:
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    properties:
      hibernate:
        show_sql: true
        format_sql: false