server:
  port: ${APP_PORT:8080}

spring:
  application:
    name: ecomap
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:ecomap}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:12345}
  jpa:
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    properties:
      hibernate:
        show_sql: true
        format_sql: false
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 15
        #generate_statistics: true
  servlet:
    multipart:
      max-file-size: 1MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: xxxxxx
    password: xxxxx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

mail:
  from: xxxxx
  to: xxxxx


path:
  images: ecopoint-images/