version: "3.9"

services:
  postgres:
    container_name: $DB_HOST
    image: postgis/postgis:14-3.3
    env_file:
      - ./.env
    ports:
      - 5432:${DB_PORT}
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./scripts/20_create_tables.sql:/docker-entrypoint-initdb.d/20_create_tables.sql
      - ./scripts/30_create_index.sql:/docker-entrypoint-initdb.d/30_create_index.sql
      - ./scripts/40_fill.sql:/docker-entrypoint-initdb.d/40_fill.sql

volumes:
  pgdata: