version: "3.9"

services:
  postgres:
    container_name: $DB_HOST
    image: postgis/postgis:14-3.3
    env_file:
      - ./.env
    ports:
      - 5432:${DB_PORT}
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

volumes:
  pgdata: